/num_pub1:
  ros__parameters:
    number : 15
    publish_period : 2.5
/num_pub2:
  ros__parameters:
    number : 20
    publish_period : 10.0
/test_param:
  ros__parameters:
    number : 20
    publish_period : 10.0
    
